name = "vue-ssr-poc"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm run build:dev"
[build.upload]
format = "modules"
main = "./index.mjs"
